<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="8df85710-5632-4c45-822d-f47fd4c7339d" name="Jacob@MANTA 2014-01-17 10:48:37" runUser="MANTA\Jacob" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="57ab9ee7-c8ea-4957-ac8f-e61444df60b2">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Jacob_MANTA 2014-01-17 10_48_37">
      <DeploymentItem filename="c:\users\jacob\documents\visual studio 2010\Projects\AssertionTestingProject\AssertionTestingProject\bin\Debug\AssertionTestingProject.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2014-01-17T10:48:37.7001256-06:00" queuing="2014-01-17T10:48:37.7071194-06:00" start="2014-01-17T10:48:37.7101211-06:00" finish="2014-01-17T10:48:37.8422132-06:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestAssertFail" storage="c:\users\jacob\documents\visual studio 2010\projects\assertiontestingproject\assertiontestspec\bin\debug\assertiontestspec.dll" id="a332c37c-a00a-ff62-446b-74d00f2c9a37">
      <Execution id="df00062c-6aba-4adf-96fa-b9fc9ebc9460" />
      <TestMethod codeBase="c:/users/jacob/documents/visual studio 2010/Projects/AssertionTestingProject/AssertionTestSpec/bin/Debug/AssertionTestSpec.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="AssertionTestSpec.AssertionTestClassTest, AssertionTestSpec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestAssertFail" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="a332c37c-a00a-ff62-446b-74d00f2c9a37" executionId="df00062c-6aba-4adf-96fa-b9fc9ebc9460" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="df00062c-6aba-4adf-96fa-b9fc9ebc9460" testId="a332c37c-a00a-ff62-446b-74d00f2c9a37" testName="TestAssertFail" computerName="MANTA" duration="00:00:00.0187949" startTime="2014-01-17T10:48:37.7121234-06:00" endTime="2014-01-17T10:48:37.8352087-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="df00062c-6aba-4adf-96fa-b9fc9ebc9460">
      <Output>
        <ErrorInfo>
          <Message>Assert.Fail failed. It doesn't matter what happens. This test fails at this line!</Message>
          <StackTrace>   at AssertionTestSpec.AssertionTestClassTest.TestAssertFail() in c:\users\jacob\documents\visual studio 2010\Projects\AssertionTestingProject\AssertionTestSpec\AssertionTestClassTest.cs:line 81
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>